### ISSUE TITLE
key error at the import

### ISSUE THREAD

**Issue by wjs9715** [seveas/python-networkmanager#32]
Hello, first of all, thank you for writing this library.
I am trying to use this on the rpi running python 3.5 in virtualenv.
When I try to import the netwokrmanager, I get below error.

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.pyenv/versions/touch-screen-3.5.2/lib/python3.5/site-packages/NetworkManager.py", line 282, in <module>
    class NetworkManager(NMDbusInterface):
  File "/home/pi/.pyenv/versions/touch-screen-3.5.2/lib/python3.5/site-packages/NetworkManager.py", line 147, in __new__
    SignalDispatcher.args[(element.attrib['name'], item.attrib['name'])] = [(arg.attrib['name'], arg.attrib['type']) for arg in item]
  File "/home/pi/.pyenv/versions/touch-screen-3.5.2/lib/python3.5/site-packages/NetworkManager.py", line 147, in <listcomp>
    SignalDispatcher.args[(element.attrib['name'], item.attrib['name'])] = [(arg.attrib['name'], arg.attrib['type']) for arg in item]
KeyError: 'name'
```

Can you let me know what am I missing?

**Comment by seveas** [comment]
Those linenumbers don't match the current version. Could you try that?

**Comment by wjs9715** [comment]
Sorry, this is the correct line numbers returned.
`>>> import NetworkManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.pyenv/versions/touch-screen-3.5.2/lib/python3.5/site-packages/NetworkManager.py", line 276, in <module>
    class NetworkManager(NMDbusInterface):
  File "/home/pi/.pyenv/versions/touch-screen-3.5.2/lib/python3.5/site-packages/NetworkManager.py", line 142, in __new__
    SignalDispatcher.args[(element.attrib['name'], item.attrib['name'])] = [(arg.attrib['name'], arg.attrib['type']) for arg in item]
  File "/home/pi/.pyenv/versions/touch-screen-3.5.2/lib/python3.5/site-packages/NetworkManager.py", line 142, in <listcomp>
    SignalDispatcher.args[(element.attrib['name'], item.attrib['name'])] = [(arg.attrib['name'], arg.attrib['type']) for arg in item]
KeyError: 'name'
>>>`

So, I have been digging, seems that introspection returned by the dbus is missing the arg name in signal.

It returns
`<signal name="DeviceRemoved">
      <arg type="o"/>
</signal>
    <signal name="DeviceAdded">
      <arg type="o"/>
    </signal>
    <signal name="PropertiesChanged">
      <arg type="a{sv}"/>
    </signal>
    <signal name="StateChanged">
      <arg type="u"/>
    </signal>
    <signal name="CheckPermissions">
    </signal>`

Can you guide to me any pointer to fix this?

**Comment by seveas** [comment]
Interesting. Which version of NetworkManager is this?

**Comment by wjs9715** [comment]
it is network-manager 0.9.10.0-7 which Ive installed by using sudo apt-get install network-manager

**Comment by seveas** [comment]
Well, bugger. Didn't test with networkmanager versions that old when writing the new signal handling.

**Comment by wjs9715** [comment]
Ah, I see. Let me try with newer version.

**Comment by seveas** [comment]
If possible, that would be the best. Was looking at the code and it'll be somewhat of a pain to support args with no names.

**Comment by wjs9715** [comment]
Using the 1.6.2, I was able to get it working. Thank you for the response!
