### ISSUE TITLE
Can't update connection settings.

### ISSUE THREAD

**Issue by yawor** [seveas/python-networkmanager#37]
Hi,

I'm trying to write a small script to temporarily switch autoconnect property to a selected Ethernet connection. Here's a code I'm testing this with:
```python
import NetworkManager

for conn in NetworkManager.Connection.all():
    settings = conn.GetSettings()
    if settings['connection']['type'] != '802-3-ethernet':
        continue

    cid = settings['connection']['id']
    ac = settings['connection'].get('autoconnect', True)

    changed = False
    if cid == '192.168.1.20' and not ac:
        del settings['connection']['autoconnect']
        changed = True
    elif ac:
        settings['connection']['autoconnect'] = False
        changed = True

    if changed:
        conn.UpdateUnsaved(settings)
```
As you can see it's nothing complicated (in the final version it would of course use command line args). Unfortunately, as soon as it tries to call `conn.UpdateUnsaved(settings)` I get following error:
```
ERROR:dbus.connection:Unable to set arguments ({'802-3-ethernet': {'auto-negotiate': False, 'mac-address': [dbus.Byte(8), dbus.Byte(98), dbus.Byte(102), dbus.Byte(86), dbus.Byte(239), dbus.Byte(31)]}, 'connection': {'id': '192.168.1.20', 'uuid': '088509ff-0a6b-4c10-a9f6-70e4d6340f0b', 'type': '802-3-ethernet', 'permissions': ['user:yawor:'], 'timestamp': 1493193712}, 'ipv6': {'method': 'ignore', 'addr-gen-mode': 0}, 'ipv4': {'method': 'manual', 'addresses': [[dbus.UInt32(335653056), dbus.UInt32(24), dbus.UInt32(0)]], 'address-data': [{'address': '192.168.1.20', 'prefix': 24}]}},) according to signature 'a{sa{sv}}': <class 'TypeError'>: Expected a string or unicode object
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    conn.UpdateUnsaved(settings)
  File "<string>", line 4, in UpdateUnsaved
  File "/home/yawor/Projects/NMTest/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/home/yawor/Projects/NMTest/lib/python3.6/site-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
```
Value of settings in that call is:
```python
{'802-3-ethernet': {'auto-negotiate': False, 'mac-address': '08:62:66:56:EF:1F', 'mac-address-blacklist': [], 's390-options': {}}, 'connection': {'id': '192.168.1.20', 'uuid': '088509ff-0a6b-4c10-a9f6-70e4d6340f0b', 'type': '802-3-ethernet', 'permissions': ['user:yawor:'], 'timestamp': 1493193712}, 'ipv6': {'method': 'ignore', 'dns': [], 'dns-search': [], 'addresses': [], 'routes': [], 'addr-gen-mode': 0, 'address-data': [], 'route-data': []}, 'ipv4': {'method': 'manual', 'dns': [], 'dns-search': [], 'addresses': [['192.168.1.20', 24, '0.0.0.0']], 'routes': [], 'address-data': [{'address': '192.168.1.20', 'prefix': 24}], 'route-data': []}, 'proxy': {}}
```
I'm using ArchLinux with NetworkManager 1.6.2-3, python 3.6 and python-networkmanager version 2.0.1.

If you need more information please feel free to ask. I can do more tests if needed.

**Comment by soloma83** [comment]
Hello.
I have gotten the same error while updating connection properties. 
Does somebody have solution?

**Comment by seveas** [comment]
Oh, that's good news. Worth making a release for :)
