### ISSUE TITLE
NM raises exception when using signals

### ISSUE THREAD

**Issue by gijzelaerr** [seveas/python-networkmanager#41]
```
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/home/gijs/Work/python-eduvpn-client/.virtualenv3/lib/python3.5/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/home/gijs/Work/python-eduvpn-client/.virtualenv3/lib/python3.5/site-packages/NetworkManager.py", line 77, in handle_signal
    receiver(sender, *(sargs + rargs), **rkwargs)
TypeError: can only concatenate list (not "tuple") to list
```

version details:
```
dbus-python==1.2.4
python-networkmanager==2.0.1
```

**Comment by seveas** [comment]
This was fixed in aea55e82cfd888e12bb4cd7b7c4fffba1a6c09ba
