### ISSUE TITLE
Failed building wheel for dbus-python

### ISSUE THREAD

**Issue by alryan** [seveas/python-networkmanager#49]
I am trying to install python-networkmanager on ubuntu 14.04 but I get this error

```
Collecting python-networkmanager
Requirement already satisfied: six in ./Envs/wifi_thesis/lib/python2.7/site-packages (from python-networkmanager)
Collecting dbus-python (from python-networkmanager)
  Using cached dbus-python-1.2.4.tar.gz
Building wheels for collected packages: dbus-python
  Running setup.py bdist_wheel for dbus-python ... error
  Complete output from command /home/al/Envs/wifi_thesis/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZROHqg/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpVDYMCApip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  creating /tmp/pip-build-ZROHqg/dbus-python/build
  creating /tmp/pip-build-ZROHqg/dbus-python/build/temp.linux-x86_64-2.7
  checking whether make supports nested variables... yes
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... no
  checking for mawk... mawk
  checking whether make sets $(MAKE)... yes
  checking whether UID '1000' is supported by ustar format... yes
  checking whether GID '1000' is supported by ustar format... yes
  checking how to create a ustar tar archive... gnutar
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking for native Windows host... no
  checking how to print strings... printf
  checking for style of include used by make... GNU
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking dependency style of gcc... gcc3
  checking for a sed that does not truncate output... /bin/sed
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /bin/dd
  checking how to truncate binary pipes... /bin/dd bs=4096 count=1
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... no
  checking for inline... inline
  checking whether /home/al/Envs/wifi_thesis/bin/python version is >= 2.6... yes
  checking for /home/al/Envs/wifi_thesis/bin/python version... 2.7
  checking for /home/al/Envs/wifi_thesis/bin/python platform... linux2
  checking for /home/al/Envs/wifi_thesis/bin/python script directory... ${prefix}/lib/python2.7/site-packages
  checking for /home/al/Envs/wifi_thesis/bin/python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
  configure: Using $PYTHON-config: /home/al/Envs/wifi_thesis/bin/python-config
  checking for Python headers using /home/al/Envs/wifi_thesis/bin/python-config --includes... -I/home/al/Envs/wifi_thesis/local/include/python2.7 -I/home/al/Envs/wifi_thesis/local/include/python2.7
  checking whether those headers are sufficient... no
  configure: error: could not find Python headers
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-ZROHqg/dbus-python/setup.py", line 106, in <module>
      'build_ext': BuildExt,
    File "/home/al/Envs/wifi_thesis/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/al/Envs/wifi_thesis/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-ZROHqg/dbus-python/setup.py", line 62, in run
      cwd=builddir)
    File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-build-ZROHqg/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/home/al/Envs/wifi_thesis/bin/python', '--prefix=/tmp/pip-build-ZROHqg/dbus-python/build/temp.linux-x86_64-2.7/prefix']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: dbus-python, python-networkmanager
  Running setup.py install for dbus-python ... error
    Complete output from command /home/al/Envs/wifi_thesis/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZROHqg/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Q1R_MF-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/al/Envs/wifi_thesis/include/site/python2.7/dbus-python:
    running install
    running build
    creating /tmp/pip-build-ZROHqg/dbus-python/build
    creating /tmp/pip-build-ZROHqg/dbus-python/build/temp.linux-x86_64-2.7
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking whether UID '1000' is supported by ustar format... yes
    checking whether GID '1000' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking whether /home/al/Envs/wifi_thesis/bin/python version is >= 2.6... yes
    checking for /home/al/Envs/wifi_thesis/bin/python version... 2.7
    checking for /home/al/Envs/wifi_thesis/bin/python platform... linux2
    checking for /home/al/Envs/wifi_thesis/bin/python script directory... ${prefix}/lib/python2.7/site-packages
    checking for /home/al/Envs/wifi_thesis/bin/python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
    configure: Using $PYTHON-config: /home/al/Envs/wifi_thesis/bin/python-config
    checking for Python headers using /home/al/Envs/wifi_thesis/bin/python-config --includes... -I/home/al/Envs/wifi_thesis/local/include/python2.7 -I/home/al/Envs/wifi_thesis/local/include/python2.7
    checking whether those headers are sufficient... no
    configure: error: could not find Python headers
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZROHqg/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/home/al/Envs/wifi_thesis/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/al/Envs/wifi_thesis/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-ZROHqg/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-ZROHqg/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/home/al/Envs/wifi_thesis/bin/python', '--prefix=/tmp/pip-build-ZROHqg/dbus-python/build/temp.linux-x86_64-2.7/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/al/Envs/wifi_thesis/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZROHqg/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Q1R_MF-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/al/Envs/wifi_thesis/include/site/python2.7/dbus-python" failed with error code 1 in /tmp/pip-build-ZROHqg/dbus-python/
```

How can I fix this?

**Comment by ilovespicynoodles** [comment]
Apparently dbus-python does not have a setup.py file, which means you will have to build it from the source here: https://pypi.python.org/pypi/dbus-python/

Tell me if that works.

**Comment by seveas** [comment]
dbus-python should be installed using your distribution's packages, not from source.
