### ISSUE TITLE
NetworkManager fails to import

### ISSUE THREAD

**Issue by anrodlo** [seveas/python-networkmanager#57]
There is already a Debian Bug Report for this, both for python and python3.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896281
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896343

After installing python-networkmanager importing the module NetworkManager
into a python interpreter fails with the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/NetworkManager.py", line 99, in <module>
    init_bus = dbus.SystemBus(private=True)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 194, in __new__
    private=private)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

**Comment by seveas** [comment]
Closing all PR's and issues prior to archiving this repository.
