### ISSUE TITLE
org.freedesktop.DBus.Error.ServiceUnknown if NetworkManager service restarts

### ISSUE THREAD

**Issue by anrodlo** [seveas/python-networkmanager#66]
If NetworkManager service restarts, it gets a new dbus unix process id. The python-networkmanager remains with the old id. since this process doesn't exist any more, a org.freedesktop.DBus.Error.ServiceUnknown exception is thrown.

The parameter follow_name_owner_changes can be used in get_object() calls to prevent this.

**Comment by tdussa** [comment]
This change prevents a regular startup on my system:
```
tdussa@aigis ~ $ python
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import NetworkManager
>>> NetworkManager.NetworkManager.Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/NetworkManager.py", line 164, in get_func
    data = self.proxy.Get(interface, name, dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3.9/site-packages/NetworkManager.py", line 261, in proxy
    self._proxy = dbus.SystemBus().get_object(self.dbus_service, self.object_path, follow_name_owner_changes=True)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 225, in get_object
    self._require_main_loop()   # we don't get the signals otherwise
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
tdussa@aigis ~ $ python
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import NetworkManager
>>> NetworkManager.NetworkManager.Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/NetworkManager.py", line 164, in get_func
    data = self.proxy.Get(interface, name, dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3.9/site-packages/NetworkManager.py", line 261, in proxy
    self._proxy = dbus.SystemBus().get_object(self.dbus_service, self.object_path, follow_name_owner_changes=True)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 225, in get_object
    self._require_main_loop()   # we don't get the signals otherwise
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
```

If I patch out the `, follow_name_owner_changes=True` in line 261 of `NetworkManager.py`, then things work again:
```
tdussa@aigis ~ $ python                                                    
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import NetworkManager
>>> NetworkManager.NetworkManager.Version
'1.28.1'
```

I'm not really sure what to make of this.  Is this expected?

Cheers,
Toby.
