### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by 0xdf-0xdf** [seveas/python-networkmanager#84]
I've installed with `pip install python-NetworkManager`.

Now I try to do anything (like get the version):

```
$ python3
Python 3.9.1+ (default, Jan 20 2021, 14:49:22) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import NetworkManager
>>> NetworkManager.NetworkManager.Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oxdf/.local/lib/python3.9/site-packages/NetworkManager.py", line 164, in get_func
    data = self.proxy.Get(interface, name, dbus_interface='org.freedesktop.DBus.Properties')
  File "/home/oxdf/.local/lib/python3.9/site-packages/NetworkManager.py", line 261, in proxy
    self._proxy = dbus.SystemBus().get_object(self.dbus_service, self.object_path, follow_name_owner_changes=True)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 225, in get_object
    self._require_main_loop()   # we don't get the signals otherwise
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
```

I've tried on both Kali and Parrot Linux with the same results.

**Comment by maggie0002** [comment]
I am getting this error on python-networkmanager==2.2 but not on python-networkmanager==2.1 (using a Raspberry Pi 4).

**Comment by razerraz** [comment]
You need to import dbus mainloop before any calls
```
from dbus.mainloop.glib import DBusGMainLoop
DBusGMainLoop(set_as_default=True)
```

**Comment by xvitaly** [comment]
Same issue on 2.2.

**Comment by xvitaly** [comment]
> You need to import dbus mainloop before any calls

This workaround works, thanks. It need to be executed directly by python-networkmanager.

**Comment by maggie0002** [comment]
> You need to import dbus mainloop before any calls
> 
> ```
> from dbus.mainloop.glib import DBusGMainLoop
> DBusGMainLoop(set_as_default=True)
> ```

Does the fact that it relies on glib imports mean that Python-NetworkManager doesn't work with Alpine Linux Docker containers (which are musl?)?

**Comment by stalkerg** [comment]
> Does the fact that it relies on glib imports mean that Python-NetworkManager doesn't work with Alpine Linux Docker containers (which are musl?)?

no, glib != glibc it's a different libs

**Comment by AndersBlomdell** [comment]
Perhaps this change to make examples work as is? 

```
--- old/NetworkManager.py	2021-06-09 12:21:36.121483128 +0200
+++ new/NetworkManager.py	2021-06-15 13:01:54.812031716 +0200
@@ -258,7 +258,8 @@
     @property
     def proxy(self):
         if not self._proxy:
-            self._proxy = dbus.SystemBus().get_object(self.dbus_service, self.object_path, follow_name_owner_changes=True)
+            self._proxy = dbus.SystemBus().get_object(self.dbus_service, self.object_path,
+                                                      follow_name_owner_changes=dbus.get_default_main_loop() != None)
             self._proxy.created = time.time()
         elif self._proxy.created < self.last_disconnect:
             if self.is_transient:
´´´

**Comment by seveas** [comment]
Closing all PR's and issues prior to archiving this repository.
