### ISSUE TITLE
import dbus

### ISSUE THREAD

**Issue by vkuehn** [seveas/python-networkmanager#86]
pip install NetworkManager route and cloning/doing/setup both complain about missing dbus even so it is installed

import NetworkManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/datadisk/git/python-networkmanager/NetworkManager.py", line 8, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

/venv.../dbus_python-1.2.16-py3.8-linux-x86_64.egg (1.2.16)

how to properly setup NetworkManager

**Comment by vkuehn** [comment]
no replay since a month. I'll not use that project anymore
