### ISSUE TITLE
org.freedesktop.NetworkManager.Settings.Failed

### ISSUE THREAD

**Issue by carloslockward** [seveas/python-networkmanager#91]
Im getting this error when trying to create a GRE Tunnel.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/snap/iotr-cr-sysmgr/x6/lib/python3.8/site-packages/sysmgr/systemmanager.py", line 941, in tunnel_config
    self.networkctrl.set_x_interface_settings(
  File "/snap/iotr-cr-sysmgr/x6/lib/python3.8/site-packages/sysmgr/networkctrl.py", line 397, in set_x_interface_settings
    connection = NMSettings.AddConnection(settings)
  File "<string>", line 4, in AddConnection
  File "/snap/iotr-cr-sysmgr/x6/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/snap/iotr-cr-sysmgr/x6/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.Settings.Failed: failure adding connection: keyfile writer produces an invalid connection: cannot access file: No such file or directory
```
This is the configuration of the connection I'm trying to add.
```
{
  'connection': {'id': 'gre-test_AutoGen',
                  'interface-name': 'gre-test',
                  'type': 'ip-tunnel'},
   'ip-tunnel': {'local': '10.10.1.49', 'mode': 2, 'remote': '10.10.2.126'},
   'ipv4': {'method': 'auto'},
   'ipv6': {'method': 'auto'}
}
```

**Comment by seveas** [comment]
Closing all PR's and issues prior to archiving this repository.
